- name: Configuring the {{COMPONENT}} Repo
  ansible.builtin.copy:
    src: mongo.repo # Location of the file on the machine where you're running this script
    dest: /etc/yum.repos.d/mongodb.repo    # 
    
- name: Installing {{COMPONENT}} Package
  ansible.builtin.package:
    name: mongodb-org
    state: present 

- name: Starting service {{COMPONENT}}
  ansible.builtin.service:
    name: mongodb-org
    state: started       