- name: Configuring the {{COMPONENT}} Repo
  ansible.builtin.copy:
    src: mongo.repo # Location of the file on the machine where you're running this script
    dest: /etc/yum.repos.d/mongodb.repo    # 
    
- name: Installing {{COMPONENT}} Package
  ansible.builtin.package:
    name: mongodb-org
    state: present 

- name: Enabling the {{COMPONENT}} visibility
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1' # value to be replaced
    replace: '0.0.0.0' # new value which should be in place of old value

- name: Starting service {{COMPONENT}}
  ansible.builtin.service:
    name: mongodb
    state: started # since it is a DB so we just start, dont just restart
    enabled: yes
    daemon-reload: yes  

- name: Download and Extract {{COMPONENT}} Schema
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp
    remote_src: yes  

- name: Injecting User Schema
  community.mongodb.mongodb_shell: # our mongo db version does not mandate the use of username and password so we dont need it    
    file: "/tmp/mongodb-main/users.js"
    idempotent: yes 

- name: Injecting Catalogue Schema
  community.mongodb.mongodb_shell: # our mongo db version does not mandate the use of username and password so we dont need it    
    file: "/tmp/mongodb-main/catalogue.js"
    idempotent: yes             