# By default , if any of the task fails in a playbook, the sub-sequent tasks won't be executed.
- name: Demo on errors
  hosts: all
  tasks:
    - name: Check Tomcat is running or not  # since this task fails, next task shipping wont run
      ansible.builtin.shell: ps -ef | grep java | grep -v grep
      register: OUT

    - name: Run the shipping
      ansible.builtin.debug:
        msg: shipping is up   
