- name: Demo on Conditions
  hosts: all
  vars:
    action: true  # action is a variable and its value is true
  tasks:
    - name: Run this task when the distribution is Centos only
      ansible.builtin.debug:
        msg: OS Distribution is {{ansible_distribution}}
      when: ansible_distribution == "CentOS"  

    - name: Run this task when the distribution is Ubuntu only
      ansible.builtin.debug:
        msg: OS Distribution is {{ansible_distribution}}
      when: ansible_distribution == "Ubuntu"  

    - name: Run this action
      ansible.builtin.debug:
        msg: Action is false
      when: action   # we declared action as a variable at the top, it will be exec if val is true
