- name: Demo on Conditions
  hosts: all
  vars:
    action: false  # action is a variable and its value is true
  tasks:
    - name: Run this task when the distribution is Centos only
      ansible.builtin.debug:
        msg: OS Distribution is {{ansible_distribution}}
      when: ansible_distribution == "CentOS"  

    - name: Run this task when the distribution is Ubuntu only
      ansible.builtin.debug:
        msg: OS Distribution is {{ansible_distribution}}
      when: ansible_distribution == "Ubuntu"  

    - name: Run this action when action is true
      ansible.builtin.debug:
        msg: Action is true
      when: action   # we declared action as a variable at the top, it will be exec if val is true, if condition is false
                     # it wont be executed
    - name: Run this action when action is not defined
      ansible.builtin.debug:
        msg: Action is undefined
      when: action is undefined                
