- name: Demo on Privilege Escalation
  hosts: all
  become: yes  # become yes means becoming root user, max privilege, runs playbook as root user/sudo, all the tasks will be executed as root user
  tasks:
    - name: Running id command # to confirm if i became root or not
      ansible.builtin.shell: id  # id means whoami in shell , SHELL module won't offer the output by default on screen, if you want you can register the output.
      register: OUT    #Output will be registered in a variable called OUT, which can be used in any of the tasks of the play

    - name: Printing the User Details
      ansible.builtin.debug:
        msg: "username is {{OUT.stdout}}"   

        # become_user: userName is the command if within a root user playbook u want to run certain tasks without root or as a particular user of your choice because become: yes makes all tasks with root privilege. 