- name: Demo on Loops
  hosts: all
  tasks:
    - name: Demo on using Loops
      ansible.builtin.debug:
        msg: "Value is {{item}}" # item is a key word, each entry is called item and will be picked on each iteration
      loop:
        - 100
        - 200
        - 300
        - 400
        - 500   