- name: Installing Erlang
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash
    
- name: Configuring {{COMPONENT}} repo
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash

- name: Installing {{COMPONENT}} Package
  ansible.builtin.package:
    name: rabbitmq-server
    state: present  

- name: Starting service {{COMPONENT}}
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: started # since it is a DB so we just start, dont just restart
    enabled: yes 

- name: Creating {{APPUSER}} user    
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present    

