- name: Installing Erlang
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash
    
- name: Configuring {{COMPONENT}} repo
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash

- name: Enabling the {{COMPONENT}} visibility
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1' # value to be replaced
    replace: '0.0.0.0' # new value which should be in place of old value

- name: Starting service {{COMPONENT}}
  ansible.builtin.systemd:
    name: mongod
    state: started # since it is a DB so we just start, dont just restart
    enabled: yes
    daemon-reload: yes  

- name: Download and Extract {{COMPONENT}} Schema
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp
    remote_src: yes  

- name: Injecting Users & Catalogue Schema
  community.mongodb.mongodb_shell: # our mongo db version does not mandate the use of username and password so we dont need it    
    file: "/tmp/mongodb-main/{{item}}.js"
    idempotent: yes 
  loop:
    - users
    - catalogue 

            