- name: Configuring the {{COMPONENT}} Repo
  ansible.builtin.copy:
    src: mysql.repo # Location of the file on the machine where you're running this script
    dest: /etc/yum.repos.d/mysql.repo    # 
    
- name: Installing {{COMPONENT}} Package
  ansible.builtin.package:
    name: mysql-community-server
    state: present 