- name: Configuring the {{COMPONENT}} Repo
  ansible.builtin.copy:
    src: mysql.repo # Location of the file on the machine where you're running this script
    dest: /etc/yum.repos.d/mysql.repo    # 
    
- name: Installing {{COMPONENT}} Package
  ansible.builtin.package:
    name: mysql-community-server
    state: present 

- name: Starting service {{COMPONENT}}
  ansible.builtin.systemd:
    name: mysqld
    state: started # since it is a DB so we just start, dont just restart
    enabled: yes  

- name: Extract the mysql log file
  ansible.builtin.slurp:
    src: /var/log/mysqld.log
    register: psw_log 

- name: Printing the password file
  debug:
    msg: "{{psw_log}}"

#- name: Extracting the password from log file
 # ansible.builtin.set_fact: # this mod helps querying the info available in a register, whereener u extracted value in a reg using var
  #  DEFAULT_PASSWORD: "{{ psw_log['content'] }}"
