- name: Configuring the {{COMPONENT}} Repo
  ansible.builtin.copy:
    src: mysql.repo # Location of the file on the machine where you're running this script
    dest: /etc/yum.repos.d/mysql.repo    # 
    
- name: Installing {{COMPONENT}} Package
  ansible.builtin.package:
    name: mysql-community-server
    state: present 

- name: Starting service {{COMPONENT}}
  ansible.builtin.systemd:
    name: mysqld
    state: started # since it is a DB so we just start, dont just restart
    enabled: yes
    daemon-reload: yes    