- name: Installing Maven
  ansible.builtin.shell: curl https://gitlab.com/thecloudcareers/opensource/-/raw/master/lab-tools/maven-java11/install.sh | bash || true

- name: Creating the user account
  ansible.builtin.include_role:
    name: common
    tasks_from: create_user  # we need to enclose appuser within quotes because we start with this var name here

- name: Downloading the artifacts
  ansible.builtin.include_role:
    name: common
    tasks_from: download_and_extract


- name: Generating the {{COMPONENT}} Artifacts
  ansible.builtin.shell: mvn clean package && mv target/{{COMPONENT}}-1.0.jar {{COMPONENT}}.jar
  args:
    chdir: /home/{{APPUSER}}/{{COMPONENT}}/ # need to specifically mention where mvn clean pckg to install

- name: Configuring and starting the service
  ansible.builtin.include_role:
    name: common
    tasks_from: config_svc   