- name: Installing Maven
  ansible.builtin.shell: curl https://gitlab.com/thecloudcareers/opensource/-/raw/master/lab-tools/maven-java11/install.sh | bash || true

- name: Creating {{APPUSER}} account
  ansible.builtin.user:
    name: "{{APPUSER}}" # we need to enclose appuser within quotes because we start with this var name here

- name: Download and Extract {{COMPONENT}} Schema
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp
    remote_src: yes    

- name: Performing {{COMPONENT}} Cleanup
  ansible.builtin.file:
    path: /home/{{APPUSER}}/{{COMPONENT}}
    state: absent    

- name: Copying {{COMPONENT}} to {{APPUSER}}
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/{{APPUSER}}/{{COMPONENT}}/
    owner: "{{APPUSER}}"
    group: "{{APPUSER}}"
    remote_src: yes

- name: Generating the {{COMPONENT}} Artifacts
  ansible.builtin.shell: mvn clean package && mv target/{{COMPONENT}}-1.0.jar {{COMPONENT}}.jar
  args:
    chdir: /home/{{APPUSER}}/{{COMPONENT}}/ # need to specifically mention where mvn clean pckg to install

- name: Copying the {{COMPONENT}} systemd file
  ansible.builtin.template:
    src: systemd.service # Location of the file on the machine where you're running this script
    dest: /etc/systemd/system/{{COMPONENT}}.service 

- name: Restarting the {{COMPONENT}} Service
  ansible.builtin.systemd:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: yes
    daemon_reload: yes   