- name: Installing Python
  ansible.builtin.package:
    name: 
      - python36
      - gcc
      - python3-devel
    state: present

- name: Creating the user account
  ansible.builtin.include_role:
    name: common
    tasks_from: create_user    

- name: Downloading the artifacts
  ansible.builtin.include_role:
    name: common
    tasks_from: download_and_extract

- name: Updating the UID in {{COMPONENT}}.ini file
  ansible.builtin.lineinfile:
    path: /home/{{APPUSER}}/{{COMPONENT}}/{{COMPONENT}}.ini
    regexp: '^uid'
    line: uid = {{USERINFO.uid}}
           
- name: Updating the GID in {{COMPONENT}}.ini file
  ansible.builtin.lineinfile:
    path: /home/{{APPUSER}}/{{COMPONENT}}/{{COMPONENT}}.ini
    regexp: '^gid'
    line: gid = {{USERINFO.group}} 

- name: Installing the app dependencies
  ansible.builtin.pip:
    requirements: /home/{{APPUSER}}/{{COMPONENT}}/requirements.txt
    executable: pip3.6  # need to add this as pip goes by python 2, we need 3.6  

- name: Configuring and starting the service
  ansible.builtin.include_role:
    name: common
    tasks_from: config_svc  

- name: Configuring the Hostname
  ansible.builtin.include_role:
    name: common
    tasks_from: set_hostname                 